//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class @case
    {
        public int caseid { get; set; }
        public string customercode { get; set; }
        public string machinecode { get; set; }
        public string casetype { get; set; }
        public string filterpack { get; set; }
        public Nullable<System.DateTime> scheduledate { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string problem { get; set; }
        public string suggest { get; set; }
        public string remarks { get; set; }
        public string completed { get; set; }
        public string followup { get; set; }
        public string castetext { get; set; }
        public string filtertext { get; set; }
    }
}
