//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class customermain
    {
        public int cindex { get; set; }
        public string contactname { get; set; }
        public string companyname { get; set; }
        public string billingaddress { get; set; }
        public string installaddress { get; set; }
        public string machinetype { get; set; }
        public string contactno { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string customer_type { get; set; }
        public string payment_type { get; set; }
        public string customercode { get; set; }
        public string invitationcode { get; set; }
        public string filterchangetime { get; set; }
        public string filterchangelitre { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public string source { get; set; }
        public string comment { get; set; }
        public string CustomerPassword { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
    }
}
