//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lead
    {
        public int idlead { get; set; }
        public string contactname { get; set; }
        public string companyname { get; set; }
        public string contactno { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string address { get; set; }
        public string comment { get; set; }
        public string customertype { get; set; }
        public Nullable<System.DateTime> leaddate { get; set; }
        public string model { get; set; }
        public string status { get; set; }
    }
}
