//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class leadaction
    {
        public int leadactionid { get; set; }
        public Nullable<int> leadid { get; set; }
        public string actiontype { get; set; }
        public string memo { get; set; }
        public Nullable<System.DateTime> nextdate { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
