//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class machine
    {
        public int mid { get; set; }
        public string machineid { get; set; }
        public string customercode { get; set; }
        public Nullable<int> customerindex { get; set; }
        public string installedaddress { get; set; }
        public Nullable<System.DateTime> installdate { get; set; }
        public Nullable<System.DateTime> nextdate { get; set; }
        public string photocode { get; set; }
        public string machinetype { get; set; }
        public string machinemodel { get; set; }
        public string mac { get; set; }
    }
}
