//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mainpack
    {
        public int mainid { get; set; }
        public string customercode { get; set; }
        public string maincheck { get; set; }
        public string havemain { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public Nullable<decimal> price { get; set; }
        public string machineid { get; set; }
        public string remarks { get; set; }
    }
}
